import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../components/landing";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
      </main>
    </>
  );
};

export default Home;
