import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../components/landing";
import Featured from "../components/landing/featured";
import Promotion from "../components/landing/promotion";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
        <Featured />
        <Promotion />
      </main>
    </>
  );
};

export default Home;
